# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wiilves
email: nikke@wiilves.se
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - Graphic Artist - User Experience Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wiilves.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
github_username:  Wiilves
facebook_username: wiilves
instagram_username: wiilves
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
linkedin_url: https://www.linkedin.com/company/15163917

# Address information
address_street: Bullsta
address_city: Stockholm
address_state: CA
address_zip: 90201

# Build settings
markdown: kramdown
